name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17 # Nâng lên Java 17 để chạy mượt mà với Gradle mới
        cache: gradle

    # THAY THẾ CHO BƯỚC LỖI: Tự động cài Android NDK chính chủ từ Google
    - name: Setup Android NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
        echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Build Zygisk Module
      run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        
        # Ép Gradle nhận diện đúng đường dẫn NDK vừa cài đặt
        ./gradlew :module:assembleRelease -Pandroid.ndkPath=$ANDROID_NDK_ROOT

    # Quét toàn bộ máy ảo để gom tất cả các file .zip được sinh ra sau khi build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.run_id }}
        path: |
          **/*.zip
        if-no-files-found: error
